server:
  port: 0

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres

  #Новое
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8890/realms/project-realm
          jwk-set-uri: http://keycloak:8890/realms/project-realm/protocol/openid-connect/certs

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://server:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
