server:
  port: 0

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8890/realms/project-realm/protocol/openid-connect/certs
          #issuer-url: http://localhost:8890/realms/project-realm

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://server:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
